//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarShopEntities : DbContext
    {
        public CarShopEntities()
            : base("name=CarShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Banner> Banner { get; set; }
        public virtual DbSet<Members> Members { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<PasswordHistory> PasswordHistory { get; set; }
        public virtual DbSet<Menus> Menus { get; set; }
        public virtual DbSet<MyFavourites> MyFavourites { get; set; }
        public virtual DbSet<RoleMenus> RoleMenus { get; set; }
        public virtual DbSet<Shops> Shops { get; set; }
        public virtual DbSet<Subscriptions> Subscriptions { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<VisitOrders> VisitOrders { get; set; }
        public virtual DbSet<Profiles> Profiles { get; set; }
        public virtual DbSet<Dealers> Dealers { get; set; }
        public virtual DbSet<DealerPersons> DealerPersons { get; set; }
        public virtual DbSet<OTPs> OTPs { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<Sells> Sells { get; set; }
        public virtual DbSet<Banners> Banners { get; set; }
        public virtual DbSet<NoticeRecords> NoticeRecords { get; set; }
        public virtual DbSet<Prepaid> Prepaid { get; set; }
        public virtual DbSet<SellsHistory> SellsHistory { get; set; }
        public virtual DbSet<BuyHistory> BuyHistory { get; set; }
        public virtual DbSet<CarCompareHistory> CarCompareHistory { get; set; }
        public virtual DbSet<ResetPwLinks> ResetPwLinks { get; set; }
        public virtual DbSet<Code> Code { get; set; }
        public virtual DbSet<Banner1> Banner1Set { get; set; }
        public virtual DbSet<Members1> Members1Set { get; set; }
        public virtual DbSet<OTPs1> OTPs1Set { get; set; }
    }
}
