//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code
    {
        public int Code_sn { get; set; }
        public int Class_sn { get; set; }
        public string Code_name { get; set; }
        public string Note1 { get; set; }
        public string Note2 { get; set; }
        public string Note3 { get; set; }
        public string Note4 { get; set; }
        public string Note5 { get; set; }
        public int Refer_sn { get; set; }
        public int Code_sort { get; set; }
        public bool Code_valid { get; set; }
        public int Note_int1 { get; set; }
        public int Note_int2 { get; set; }
        public int Note_int3 { get; set; }
        public int Note_int4 { get; set; }
        public int Note_int5 { get; set; }
        public int Note_int6 { get; set; }
        public int Note_int7 { get; set; }
        public int Note_int8 { get; set; }
        public int Note_int9 { get; set; }
        public int Note_int10 { get; set; }
    }
}
