//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealers
    {
        public long seq { get; set; }
        public string area { get; set; }
        public string dealerName { get; set; }
        public string businessOffice { get; set; }
        public string telAreaCode { get; set; }
        public string tel { get; set; }
        public string address { get; set; }
        public string gmap { get; set; }
        public string businessStartHourDay { get; set; }
        public string businessEndHourDay { get; set; }
        public string businessStartHourNight { get; set; }
        public string businessEndHourNight { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string type { get; set; }
        public string email { get; set; }
        public string brand { get; set; }
        public string businessOffice2 { get; set; }
        public string picture { get; set; }
        public string busDay { get; set; }
        public string dealerCode { get; set; }
    }
}
