//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long seq { get; set; }
        public string action { get; set; }
        public string request { get; set; }
        public string response { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string eventLevel { get; set; }
        public string creator { get; set; }
    }
}
