//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        public long seq { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public string mobile { get; set; }
        public string title { get; set; }
        public string birthday { get; set; }
        public string address { get; set; }
        public string interestedCar { get; set; }
        public Nullable<bool> isMailVerify { get; set; }
        public Nullable<bool> isMobileVerify { get; set; }
        public string id { get; set; }
        public Nullable<bool> needToChangeFirst { get; set; }
        public Nullable<bool> status { get; set; }
        public string brand { get; set; }
        public string area { get; set; }
    }
}
