//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prepaid
    {
        public long seq { get; set; }
        public string prepaidNo { get; set; }
        public string shopNo { get; set; }
        public string user_id { get; set; }
        public string name { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string title { get; set; }
        public string id { get; set; }
        public string birthday { get; set; }
        public string address { get; set; }
        public string contactPeriod { get; set; }
        public string others { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string paidStatus { get; set; }
        public string contactStatus { get; set; }
        public string sales { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> contactTime { get; set; }
        public string serveSales { get; set; }
        public string brand { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public string returnReason { get; set; }
        public string action { get; set; }
        public string formalNo { get; set; }
        public string isClose { get; set; }
        public string status { get; set; }
    }
}
