//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sells
    {
        public long seq { get; set; }
        public string brand { get; set; }
        public string licensePlate { get; set; }
        public string licensePicture { get; set; }
        public int milage { get; set; }
        public int yearOfManufacture { get; set; }
        public string carModel { get; set; }
        public string displacement { get; set; }
        public string area { get; set; }
        public string owner { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
        public string dealer { get; set; }
        public string salesRep { get; set; }
        public string carCondition1 { get; set; }
        public string carCondition2 { get; set; }
        public string carCondition3 { get; set; }
        public string carCondition4 { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string contactPeriod { get; set; }
        public string yearMonthOfManufacture { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public string sellNo { get; set; }
        public int price { get; set; }
        public string status { get; set; }
        public string consultant { get; set; }
        public string contactTime { get; set; }
        public string process { get; set; }
        public string note { get; set; }
        public string formalSellNo { get; set; }
        public string liveArea { get; set; }
        public string address { get; set; }
        public string isBuyNewCar { get; set; }
        public string loseReason { get; set; }
        public bool needConsult { get; set; }
        public string stronghold { get; set; }
        public string birthday { get; set; }
        public string action { get; set; }
        public string carBrand { get; set; }
        public string otherBrand { get; set; }
    }
}
