//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitOrders
    {
        public long seq { get; set; }
        public string visitCarType { get; set; }
        public string visitCarYear { get; set; }
        public string dealerName { get; set; }
        public string dealerAddress { get; set; }
        public string dealerTel { get; set; }
        public string name { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string title { get; set; }
        public string id { get; set; }
        public string birthday { get; set; }
        public string address { get; set; }
        public string salesRep { get; set; }
        public string others { get; set; }
        public string period { get; set; }
        public Nullable<bool> isConfirmed { get; set; }
        public string verifyCode { get; set; }
        public Nullable<System.DateTime> verifyCodeValidTime { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public string assignedConsultant { get; set; }
        public string consultant { get; set; }
        public string status { get; set; }
        public string shopNo { get; set; }
        public System.DateTime visitTime { get; set; }
        public string brand { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public string loseReason { get; set; }
        public string loseReason2 { get; set; }
        public string action { get; set; }
        public string formalNo { get; set; }
        public string isClose { get; set; }
        public string visitCarModel { get; set; }
    }
}
